name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: test

      - name: Unit tests report
        uses: dorny/test-reporter@v1
        if: always()
        with:
            name: JUnit Test Report
            path: ./*/build/test-results/*/TEST-*.xml
            reporter: java-junit
            fail-on-error: true

  android_tests:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 26, 32]
        target: [default, google_apis]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew cAT

  assemble_debug:
    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: apk-debug
          path: app/build/outputs/apk/*/debug/*.apk