name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  detekt:
    name: "Detekt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Cache Gradle and Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Unit tests
        run: ./gradlew detekt

      - name: Add Detekt report
        if: success() || failure()
        run: cat ./app/build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY

  unit_tests:
    needs: [ detekt ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Cache Gradle and Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Unit tests
        run: ./gradlew test

  android_tests:
    needs: [ detekt ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Cache Gradle and Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

  assemble_debug:
    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Cache Gradle and Wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Generate APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: apk-debug
          path: app/build/outputs/apk/*/debug/*.apk