name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Root
      uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
       git config --global url."https://github.com/".insteadOf "git@github.com:"
       auth_header="$(git config --local --get http.https://github.com/.extraheader)"
       git submodule sync --recursive
       git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build
