name: Fastlane
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v1
        with:
           fastlaneDir: ./fastlane # optional. default is './fastlane'.
           # enable check to validate if a locale is supported by the Play Store Listing.
           usePlayStoreLocales: true # optional. default is false.